//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cross.StockInfo.Assets.Strings {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cross.StockInfo.Assets.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 海岬型(BCI) 的當地語系化字串。
        /// </summary>
        public static string BCIIndex_Label {
            get {
                return ResourceManager.GetString("BCIIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 散裝船航運運價指標 的當地語系化字串。
        /// </summary>
        public static string BDIIndex_ChartTitle {
            get {
                return ResourceManager.GetString("BDIIndex_ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 波羅的海綜合指數(BDI) 的當地語系化字串。
        /// </summary>
        public static string BDIIndex_Label {
            get {
                return ResourceManager.GetString("BDIIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 巴拿馬型(BPI) 的當地語系化字串。
        /// </summary>
        public static string BPIIndex_Label {
            get {
                return ResourceManager.GetString("BPIIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢BDI指數發生錯誤 : {0} 的當地語系化字串。
        /// </summary>
        public static string Exception_QueryBdiRepotError {
            get {
                return ResourceManager.GetString("Exception_QueryBdiRepotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢BPI指數發生錯誤 : {0} 的當地語系化字串。
        /// </summary>
        public static string Exception_QueryBpiRepotError {
            get {
                return ResourceManager.GetString("Exception_QueryBpiRepotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幅度 的當地語系化字串。
        /// </summary>
        public static string Stock_ChangePercentage {
            get {
                return ResourceManager.GetString("Stock_ChangePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 漲跌 的當地語系化字串。
        /// </summary>
        public static string Stock_ChangeRange {
            get {
                return ResourceManager.GetString("Stock_ChangeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 價格 的當地語系化字串。
        /// </summary>
        public static string Stock_Price {
            get {
                return ResourceManager.GetString("Stock_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輕便型(Supramax) 的當地語系化字串。
        /// </summary>
        public static string SupermaxIndex_Label {
            get {
                return ResourceManager.GetString("SupermaxIndex_Label", resourceCulture);
            }
        }
    }
}
